### ISSUE TITLE
curl version

### ISSUE THREAD

**Issue by rafajor** [vrdominguez/dinaip-docker#2]
Hi I have been using this docker for a long time but today when I tried to build from a new machine, it failed. Apparently it's because of the curl version, I have removed the version requirement and it seems to work correctly.

**Comment by vrdominguez** [comment]
Hello @rafajor,

I use a fixed version of curl in docker files to keep the image reproducible, but it seems that it is not available in the repositories anymore, I will take a look at this as soon as I can and check if I should always use the latest version or update with the new stable.

Cheers,
Víctor

**Comment by vrdominguez** [comment]
Hello @rafajor,

I'll be merging PR #3 soon, which updates the curl version for both the Debian and Alpine containers.

However, I want to bring to your attention a potential issue with dinaip in the future, as it's using the deprecated smart match operator (`~~`), which is indicated in the log:

```log
Smartmatch is deprecated at /usr/sbin/dinaip line 356.
```

Since this operator is deprecated, it’s likely to be removed from Perl in the future. When that happens, the application will no longer work unless it's updated to remove the smart match usage.

To minimize log noise in the Alpine container, I’ve added a temporary workaround that suppresses the deprecation warnings. However, this is only a short-term solution and will break once the operator is officially removed from Perl.

Best regards,
Víctor

**Comment by rafajor** [comment]
Thank you @vrdominguez
